import { StyleSheet, Dimensions } from "react-native";

const { width: winWidth } = Dimensions.get("window");

export default StyleSheet.create({
	modal: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	body: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		flexGrow: 0.3,
		borderRadius: 10,
		width: winWidth - 100,
		backgroundColor: "#f2e9e1",
		padding: 40,
	},
	textInput: {
		marginBottom: 35,
		textAlign: "center",
		fontWeight: "bold",
		fontSize: 17,
		borderWidth: 1,
		borderColor: "black",
		borderRadius: 5,
		paddingHorizontal: 10,
		// paddingTop: 10,
		// paddingBottom: 10,
	},
	icon: {
		fontSize: 60,
		marginHorizontal: 10,
		// margintop: 10,
		// marginBottom: 10,
		textAlign: "center",
	},
	colorOptionsContainer: {
		flexDirection: "row",
		justifyContent: "space-around",
		padding: 10,
		paddingHorizontal: 20,
		// paddingBottom: 20,
		// paddingTop: 20,
		borderWidth: 1,
		borderColor: "black",
		borderRadius: 5,
		marginBottom: 35,
	},
	colorOption: {
		width: 35,
		height: 35,
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	button: {
		paddingTop: 10,
		paddingBottom: 10,
		marginHorizontal: 10,
		marginVertical: 40,
		// marginBottom: 10,
		// marginTop: 10,
		// marginLeft: 40,
		// marginRight: 40,
		paddingVertical: 20,
		// paddingLeft: 20,
		// paddingRight: 20,
		borderWidth: 1,
		borderColor: "black",
		borderRadius: 5,
		textAlign: "center",
		fontWeight: "bold",
		fontSize: 17,
	},
	text: {
		textAlign: "center",
		fontWeight: "bold",
		fontSize: 17,
	},
	checkmark: {
		position: "absolute",
		top: "50%",
		left: "50%",
		transform: [{ translateX: -12 }, { translateY: -12 }],
		color: "white",
		fontSize: 24,
	},
	// submit: {
	// 	margin: 25,
	// 	fontSize: 17,
	// 	borderWidth: 2,
	// 	borderColor: "black",
	// 	borderRadius: 5,
	// 	paddingTop: 10,
	// 	paddingBottom: 10,
	// },
});
