import { StyleSheet } from "react-native";

export default StyleSheet.create({
	textInput: {
		marginBottom: 35,
		textAlign: "center",
		fontWeight: "bold",
		fontSize: 17,
		borderWidth: 1,
		borderColor: "black",
		borderRadius: 5,
		paddingTop: 10,
		paddingBottom: 10,
	},
	colorOptionsContainer: {
		flexDirection: "row",
		justifyContent: "space-around",
		padding: 10,
		paddingBottom: 20,
		paddingTop: 20,
		borderWidth: 1,
		borderColor: "black",
		borderRadius: 5,
		marginBottom: 35,
	},
	colorOption: {
		width: 35,
		height: 35,
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	button: {
		paddingTop: 10,
		paddingBottom: 10,
		marginBottom: 10,
		marginTop: 10,
		marginLeft: 40,
		marginRight: 40,
		paddingLeft: 20,
		paddingRight: 20,
		borderWidth: 1,
		borderColor: "black",
		borderRadius: 5,
		textAlign: "center",
		fontWeight: "bold",
		fontSize: 17,
	},
	text: {
		textAlign: "center",
		fontWeight: "bold",
		fontSize: 17,
	},
	checkmark: {
		position: "absolute",
		top: "50%",
		left: "50%",
		transform: [{ translateX: -12 }, { translateY: -12 }],
		color: "white",
		fontSize: 24,
	},
});
